### ISSUE TITLE
Checkboxes are not checked with lazy default values + Material UI

### ISSUE THREAD

**Issue by derekshih** [wellyshen/react-cool-form#574]
# Bug Report

## Describe the Bug

When using Material UI + lazy default values,  checkboxes & radio buttons are not checked.

## How to Reproduce

Add a MUI checkbox to a form, and set corresponding field to `true` by lazy default values.

Please see sandbox link below.

## CodeSandbox Link

https://codesandbox.io/s/rcf-material-ui-lazy-default-5e0uq

## Expected Behavior

The checkbox should be checked initially.

## Your Environment

- OS: MacOS
- Browser: Chrome
- Version: 89

**Comment by wellyshen** [comment]
@derekshih Thank you for giving this library a try. Because the `<Checkbox />` and `<RadioGroup />` are designed as controlled component, so we need to initialize the UI as below:

```diff
    <FormControlLabel control={<Checkbox />} name="single" label="single" />
+  <FormControlLabel control={<Checkbox defaultChecked />} name="single" label="single" />

    <RadioGroup name="mood" aria-label="mood" row>
+  <RadioGroup name="mood" aria-label="mood" row defaultValue="😊">  
```
