### ISSUE TITLE
Reset only works after focus with useControlled

### ISSUE THREAD

**Issue by nilscorver** [wellyshen/react-cool-form#695]
# Bug Report

## Describe the Bug

When using `useControlled` to control a field, the reset function of the form does not change the value until you have focussed the field.

## How to Reproduce

Using your Lazy Default Values example.

```
...

const ControlledField = ({ name, ...rest }) => {
  const [fieldProps] = useControlled(name);

  return <Field {...rest} {...fieldProps} />;
};

function App() {
  const { form, reset } = useForm({
    defaultValues: { firstName: "Test", lastName: "123" },
    onReset: (values) => console.log("onReset: ", values)
  });

  // This doesn't work, only after focus.
  useEffect(() => reset({ firstName: "Welly", lastName: "Shen" }), [reset]);

  return (
    <form ref={form}>
      <ControlledField label="First Name" id="first-name" name="firstName" />
      <Field label="Last Name" id="last-name" name="lastName" />
      <input type="submit" />

      {/* This doesn't work, only after focus. */}
      <button type="button" onClick={() => reset({ firstName: "henk" })}>Manual</button>
    </form>
  );
}

```

## CodeSandbox Link

Show me the bug on [CodeSandbox](https://codesandbox.io/s/rcf-lazy-default-values-forked-nc7di?file=/index.js).

## Expected Behavior

It should receive the new value after reset.

## Your Environment

- Device: Mac
- Browser: Chrome / FireFox

**Comment by wellyshen** [comment]
@nilscorver Thank you for reporting this bug, will fix it soon.

**Comment by nilscorver** [comment]
Ps. love the library, using Formik and react-hook-form, this feels like a breeze! Keep up the good work!
