### ISSUE TITLE
Still being maintained? 

### ISSUE THREAD

**Issue by mmahalwy** [wellyshen/react-cool-form#789]
Package still being maintained?

**Comment by mmahalwy** [comment]
Cc @wellyshen

**Comment by wellyshen** [comment]
@mmahalwy Of course, but it's not stable yet, APIs might be changed in the near future.

**Comment by mmahalwy** [comment]
@wellyshen what can i help with?

**Comment by mmahalwy** [comment]
i have a few ideas id like to contribute to the lib if youre open to it!

**Comment by wellyshen** [comment]
@mmahalwy Just need time to deal with [this issue](https://github.com/wellyshen/react-cool-form/issues/700#issue-951484475) from my side. What kind of idea do you have?

**Comment by mmahalwy** [comment]
1. id like to allow the field `defaultValue` to force override the `defaultValues` on `useForm`. Regardless if its `reset` or not.
