### ISSUE TITLE
useForm just not working

### ISSUE THREAD

**Issue by FrameMuse** [wellyshen/react-cool-form#859]
## Description

I want to use `react-cool-form` to only get state

BUT

When I try to use the hook, it's not working properly
- It doesn't prevent default of the form
- It's not update state (it's always init state)

Example of my code
```tsx
function Component(props: ComponentProps) {
  const { form, submit } = useForm<DeepPartial<MentorPatchType>>()

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    const state = await submit(event)
    const values = state.values

    console.log(values) // The init state, not changing when I change inputs but, in the examples I've seen, it should work!
  }

  return (
    <form ref={form} onSubmit={onSubmit}>
      <input type="submit" />
    </form>
  )
}
```

I used the simplest code ever, though it's still not working
```tsx
function Component(props: ComponentProps) {
  const { form } = useForm<DeepPartial<MentorPatchType>>()
  return (
    <form ref={form}>
      <input type="submit" />
    </form>
  )
}
```

## The question
What am I doing wrong?

**Comment by wellyshen** [comment]
@FrameMuse Please refer the [example](https://github.com/wellyshen/react-cool-form#quick-start)

**Comment by FrameMuse** [comment]
I copy/paste the example and it still doesn't work. I also tested my code in codesandbox and it seems to work. I can't really understand what is happening 😞
